# Generated by Django 5.0.3 on 2024-06-11 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0002_incometaxpofile_incometaxbankdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incometaxaddress',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='incometaxbankdetails',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='password',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='incometaxaddress',
            name='username',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='incometaxbankdetails',
            name='username',
        ),
        migrations.CreateModel(
            name='IncomeTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('marital_status', models.IntegerField(blank=True, choices=[(1, 'married'), (2, 'unmarried'), (3, 'prefer not to disclose')])),
                ('aadhar_no', models.CharField(blank=True, max_length=12)),
                ('aadhar_enrollment_no', models.CharField(blank=True, max_length=28)),
                ('pan_no', models.CharField(blank=True, max_length=10)),
                ('mobile_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number can be only 10 digits.', regex='^([1-9][0-9]{9})$')])),
                ('email', models.EmailField(max_length=254)),
                ('residential_status', models.IntegerField(blank=True, choices=[(1, 'Indian Resident'), (2, 'Non-Resident Indian'), (3, 'Resident But Not Ordinarily Resident Indian')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='incometaxaddress',
            name='income_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='incometaxbankdetails',
            name='income_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incomeTax.incometaxprofile'),
        ),
        migrations.DeleteModel(
            name='IncomeTaxPofile',
        ),
    ]
