# Generated by Django 5.0.3 on 2024-06-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0003_alter_incometaxaddress_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxaddress',
            name='income_tax',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_address', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='incometaxbankdetails',
            name='income_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_tax_bankdetails', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
