# Generated by Django 5.0.3 on 2024-06-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0004_alter_incometaxaddress_income_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxaddress',
            name='income_tax',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='incomeTax.incometaxprofile'),
        ),
    ]
