# Generated by Django 5.0.3 on 2024-06-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0007_alter_incometaxreturnyears_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometaxreturnyears',
            name='name',
        ),
    ]
