# Generated by Django 5.0.3 on 2024-06-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0008_remove_incometaxreturnyears_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxreturnyears',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
