# Generated by Django 5.0.3 on 2024-07-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0009_incometaxreturnyears_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('question', models.CharField(max_length=255)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Indian Resident'), (2, 'Non-Resident Indian'), (3, 'IndianResident(NotOrdinary)'), (4, 'IndianResident(Ordinary)')])),
                ('income_tax_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_statuses', to='incomeTax.incometaxprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
