# Generated by Django 5.0.3 on 2024-07-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0010_residentialstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialstatus',
            name='status',
        ),
    ]
