# Generated by Django 5.0.3 on 2024-07-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0013_remove_residentialstatus_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialstatusanswer',
            name='income_tax',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='status_answers', to='incomeTax.incometaxprofile'),
            preserve_default=False,
        ),
    ]
