# Generated by Django 5.0.3 on 2024-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0015_alter_residentialstatusanswer_income_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialstatusanswer',
            name='next_question',
        ),
        migrations.AddField(
            model_name='residentialstatus',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
