# Generated by Django 5.0.3 on 2024-07-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0016_remove_residentialstatusanswer_next_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialstatus',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
