# Generated by Django 5.0.3 on 2024-07-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0017_alter_residentialstatus_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResidentialStatus',
            new_name='ResidentialStatusQuestions',
        ),
    ]
