# Generated by Django 5.0.3 on 2024-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0018_rename_residentialstatus_residentialstatusquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialstatusquestions',
            name='sequence',
            field=models.BooleanField(default=False),
        ),
    ]
