# Generated by Django 5.0.3 on 2024-07-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0019_residentialstatusquestions_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialstatusquestions',
            name='options_type',
            field=models.IntegerField(choices=[(1, 'Toggled Buttons'), (2, 'Drop Down'), (3, 'Radio Buttons'), (4, 'Auto Complete'), (5, 'Multi Select')], default=1),
        ),
    ]
