# Generated by Django 5.0.3 on 2024-07-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0021_alter_incometaxprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxprofile',
            name='is_pan_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
