# Generated by Django 5.0.3 on 2024-07-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0022_incometaxprofile_is_pan_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(max_length=255)),
                ('tan', models.CharField(max_length=255)),
                ('employer_category', models.IntegerField(choices=[(1, 'Private'), (2, 'Central Government'), (3, 'State Government'), (4, 'Public Sector Unit')])),
                ('tds_deduction', models.DecimalField(decimal_places=2, max_digits=30)),
                ('income_reported', models.DecimalField(decimal_places=2, max_digits=30)),
                ('upload_form_type', models.IntegerField(choices=[(1, 'Form16'), (2, 'Pay Slips')])),
                ('upload_form_file', models.FileField(upload_to='salary_income_document_files/')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=30)),
                ('basic_salary_component', models.DecimalField(decimal_places=2, max_digits=30)),
                ('hra_component', models.DecimalField(decimal_places=2, max_digits=30)),
                ('annual_rent_paid', models.DecimalField(decimal_places=2, max_digits=30)),
                ('do_you_live_in_these_cities', models.BooleanField()),
                ('income_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_incomes', to='incomeTax.incometaxprofile')),
                ('income_tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_incomes', to='incomeTax.incometaxreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
