# Generated by Django 5.0.3 on 2024-07-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0022_incometaxprofile_is_pan_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxprofile',
            name='is_data_imported',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
