# Generated by Django 5.0.3 on 2024-07-18 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0024_rentalincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalGains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.IntegerField(choices=[(1, 'House Property'), (2, 'ListedShares/MutualFunds')])),
                ('ownership_percent', models.IntegerField(max_length=3)),
                ('purchase_date', models.DateField()),
                ('sale_date', models.DateField()),
                ('held_for_no_of_days', models.IntegerField(max_length=3)),
                ('sale_consideration', models.DecimalField(decimal_places=2, max_digits=30)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('transfer_expense', models.DecimalField(decimal_places=2, max_digits=30)),
                ('improvement_expense', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('gain_or_loss', models.DecimalField(decimal_places=2, max_digits=30)),
                ('property_door_no', models.CharField(max_length=255)),
                ('property_area', models.CharField(max_length=255)),
                ('property_city', models.CharField(max_length=255)),
                ('property_pin', models.CharField(max_length=255)),
                ('property_state', models.CharField(max_length=255)),
                ('property_country', models.CharField(max_length=255)),
                ('stt_paid', models.BooleanField()),
                ('isn_code', models.CharField(max_length=255)),
                ('fund_date', models.DateField()),
                ('fair_value_per_unit', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sale_price_per_unit', models.DecimalField(decimal_places=2, max_digits=30)),
                ('purchase_price_per_unit', models.DecimalField(decimal_places=2, max_digits=30)),
                ('no_of_units', models.IntegerField(max_length=30)),
                ('income_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_gains', to='incomeTax.incometaxprofile')),
                ('income_tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_gains', to='incomeTax.incometaxreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=255)),
                ('aadhar', models.CharField(max_length=255)),
                ('percentage_of_ownership', models.IntegerField(max_length=3)),
                ('capital_gains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_details', to='incomeTax.capitalgains')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
