# Generated by Django 5.0.3 on 2024-07-18 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0025_capitalgains_buyerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_income_type', models.IntegerField(choices=[('44AD', '44AD'), ('44ADA', '44ADA')])),
                ('business_name', models.CharField(max_length=255)),
                ('industry', models.IntegerField(choices=[(1, 'House Property'), (2, 'ListedShares/MutualFunds')])),
                ('nature_of_business', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('gross_receipt_cheq_neft_rtgs_turnover', models.DecimalField(decimal_places=2, max_digits=30)),
                ('gross_receipt_cheq_neft_rtgs_profit', models.DecimalField(decimal_places=2, max_digits=30)),
                ('gross_receipt_cash_upi_turnover', models.DecimalField(decimal_places=2, max_digits=30)),
                ('gross_receipt_cash_upi_profit', models.DecimalField(decimal_places=2, max_digits=30)),
                ('fixed_asset', models.DecimalField(decimal_places=2, max_digits=30)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=30)),
                ('receivebles', models.DecimalField(decimal_places=2, max_digits=30)),
                ('loans_and_advances', models.DecimalField(decimal_places=2, max_digits=30)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cash_in_hand', models.DecimalField(decimal_places=2, max_digits=30)),
                ('bank_balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('other_assets', models.DecimalField(decimal_places=2, max_digits=30)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=30)),
                ('secured_loans', models.DecimalField(decimal_places=2, max_digits=30)),
                ('payables', models.DecimalField(decimal_places=2, max_digits=30)),
                ('unsecured_loans', models.DecimalField(decimal_places=2, max_digits=30)),
                ('advances', models.DecimalField(decimal_places=2, max_digits=30)),
                ('other_liabilities', models.DecimalField(decimal_places=2, max_digits=30)),
                ('income_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_income', to='incomeTax.incometaxprofile')),
                ('income_tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_income', to='incomeTax.incometaxreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
