# Generated by Django 5.0.3 on 2024-07-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0026_businessincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expences', models.DecimalField(decimal_places=2, max_digits=30)),
                ('gross_recipts', models.DecimalField(decimal_places=2, max_digits=30)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=30)),
                ('previous_unabsorbed_losses', models.DecimalField(decimal_places=2, max_digits=30)),
                ('income_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_income', to='incomeTax.incometaxprofile')),
                ('income_tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_income', to='incomeTax.incometaxreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.CharField(max_length=255)),
                ('measurement', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pincode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('land_status', models.IntegerField(choices=[(1, 'Own'), (2, 'Held on lease')])),
                ('water_source', models.IntegerField(choices=[(1, 'Irrigated'), (2, 'Rain-fed')])),
                ('agriculture_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='incomeTax.agricultureincome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
