# Generated by Django 5.0.3 on 2024-07-18 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0029_deductions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssesmentAndAdvanceTaxPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bsr_code', models.CharField(max_length=255)),
                ('challan_no', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('upload_challan', models.FileField(upload_to='tax_paid_challan_document_files/')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.deductions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TdsOrTcsDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_of_deductor', models.CharField(max_length=255)),
                ('tan', models.CharField(max_length=255)),
                ('tds_or_tcs_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('gross_receipts', models.DecimalField(decimal_places=2, max_digits=30)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.deductions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
