# Generated by Django 5.0.3 on 2024-07-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0030_selfassesmentandadvancetaxpaid_tdsortcsdeduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassesmentandadvancetaxpaid',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='tdsortcsdeduction',
            name='deduction',
        ),
        migrations.AddField(
            model_name='selfassesmentandadvancetaxpaid',
            name='income_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.incometaxprofile'),
        ),
        migrations.AddField(
            model_name='selfassesmentandadvancetaxpaid',
            name='income_tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.incometaxreturn'),
        ),
        migrations.AddField(
            model_name='tdsortcsdeduction',
            name='income_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.incometaxprofile'),
        ),
        migrations.AddField(
            model_name='tdsortcsdeduction',
            name='income_tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.incometaxreturn'),
        ),
    ]
