# Generated by Django 5.0.3 on 2024-07-18 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0031_remove_selfassesmentandadvancetaxpaid_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesmentandadvancetaxpaid',
            name='income_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='selfassesmentandadvancetaxpaid',
            name='income_tax_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.incometaxreturn'),
        ),
    ]
