# Generated by Django 5.0.3 on 2024-07-18 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0032_alter_selfassesmentandadvancetaxpaid_income_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassesmentandadvancetaxpaid',
            name='income_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='selfassesmentandadvancetaxpaid',
            name='income_tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_assesment_and_advance_tax_paid', to='incomeTax.incometaxreturn'),
        ),
        migrations.AlterField(
            model_name='tdsortcsdeduction',
            name='income_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='tdsortcsdeduction',
            name='income_tax_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.incometaxreturn'),
        ),
    ]
