# Generated by Django 5.0.3 on 2024-07-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0033_alter_selfassesmentandadvancetaxpaid_income_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='home_loan_taken_year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tdsortcsdeduction',
            name='income_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='tdsortcsdeduction',
            name='income_tax_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_or_tcs_deduction', to='incomeTax.incometaxreturn'),
        ),
    ]
