# Generated by Django 5.0.3 on 2024-07-19 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0034_alter_deductions_home_loan_taken_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemptincome',
            name='exempt_income_type',
        ),
        migrations.RemoveField(
            model_name='exemptincome',
            name='interest_amount',
        ),
        migrations.AddField(
            model_name='exemptincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='exemptincome',
            name='exemption_type',
            field=models.IntegerField(choices=[(1, 'Irrigated'), (2, 'NRE A/C'), (3, 'others')], default=1),
        ),
        migrations.AddField(
            model_name='exemptincome',
            name='particular',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exemptincome',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exemptincome',
            name='income_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exempt_incomes_agriculture', to='incomeTax.incometaxprofile'),
        ),
        migrations.AlterField(
            model_name='exemptincome',
            name='income_tax_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exempt_incomes_agriculture', to='incomeTax.incometaxreturn'),
        ),
        migrations.CreateModel(
            name='InterestIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_income_type', models.IntegerField(choices=[(1, 'Savings Bank A/c'), (2, 'Fixed deposits'), (3, 'others')])),
                ('description', models.CharField(max_length=255)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('income_tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exempt_incomes', to='incomeTax.incometaxprofile')),
                ('income_tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exempt_incomes', to='incomeTax.incometaxreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ExemptIncomeInAgriculture',
        ),
    ]
