# Generated by Django 5.0.3 on 2024-07-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0035_remove_exemptincome_exempt_income_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdetails',
            name='percentage_of_ownership',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='held_for_no_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='no_of_units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='ownership_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalincome',
            name='ownership_percent',
            field=models.IntegerField(),
        ),
    ]
