# Generated by Django 5.0.3 on 2024-07-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0023_incometaxprofile_is_data_imported'),
        ('incomeTax', '0037_alter_businessincome_industry'),
    ]

    operations = [
    ]
