# Generated by Django 5.0.3 on 2024-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0042_alter_deductions_income_tax_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestonitrefunds',
            name='interest_on_it_refunds_status',
            field=models.IntegerField(choices=[(1, 'Received'), (2, 'Pending')], default=2),
        ),
    ]
