# Generated by Django 5.0.3 on 2024-07-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0043_interestonitrefunds_interest_on_it_refunds_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalincome',
            name='tenant_aadhar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalincome',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalincome',
            name='tenant_pan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
