# Generated by Django 5.0.3 on 2024-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0045_capitalgains_term_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalgains',
            name='fair_value_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='fund_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='isn_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='no_of_units',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='property_area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='property_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='property_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='property_door_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='property_pin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='property_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='purchase_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='sale_price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='stt_paid',
            field=models.BooleanField(null=True),
        ),
    ]
