# Generated by Django 5.0.3 on 2024-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0046_alter_capitalgains_fair_value_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalgains',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='ownership_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='capitalgains',
            name='sale_consideration',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
