# Generated by Django 5.0.3 on 2024-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0047_alter_capitalgains_amount_alter_capitalgains_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalgains',
            name='improvement_expense',
            field=models.BooleanField(null=True),
        ),
    ]
