# Generated by Django 5.0.3 on 2024-07-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0048_alter_capitalgains_improvement_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalgains',
            name='fund_date',
        ),
    ]
