# Generated by Django 5.0.3 on 2024-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0049_remove_capitalgains_fund_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxreturn',
            name='upload_26as',
            field=models.FileField(blank=True, upload_to='26as_documents/'),
        ),
        migrations.AddField(
            model_name='incometaxreturn',
            name='upload_ais',
            field=models.FileField(blank=True, upload_to='ais_documents/'),
        ),
    ]
