# Generated by Django 5.0.3 on 2024-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0051_rename_upload_ais_incometaxreturn_ais_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsortcsdeduction',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
