# Generated by Django 5.0.3 on 2024-08-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0052_tdsortcsdeduction_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfassesmentandadvancetaxpaid',
            old_name='upload_challan',
            new_name='challan_pdf',
        ),
    ]
