# Generated by Django 5.0.3 on 2024-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0053_rename_upload_challan_selfassesmentandadvancetaxpaid_challan_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='incometaxprofile',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(1, 'married'), (2, 'unmarried'), (3, 'prefer not to disclose')], null=True),
        ),
    ]
