# Generated by Django 5.0.3 on 2024-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0054_alter_incometaxprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometaxprofile',
            name='residential_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Indian Resident'), (2, 'Non-Resident Indian'), (3, 'IndianResident(NotOrdinary)'), (4, 'IndianResident(Ordinary)')], null=True),
        ),
    ]
