# Generated by Django 5.0.3 on 2024-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0055_alter_incometaxprofile_residential_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxreturn',
            name='tis_pdf',
            field=models.FileField(blank=True, upload_to='tis_documents/'),
        ),
    ]
