# Generated by Django 5.0.3 on 2024-09-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomeTax', '0056_incometaxreturn_tis_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regime_json_data', models.JSONField()),
                ('regime_type', models.IntegerField(choices=[(1, 'new'), (2, 'old')])),
                ('income_tax_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computations', to='incomeTax.incometaxreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
