# Generated by Django 5.0.3 on 2024-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_screen_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Partially Paid'), (2, 'Paid'), (3, 'Failed')], default=0),
        ),
    ]
