# Generated by Django 5.0.3 on 2024-03-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprecord',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='otp_session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
