# Generated by Django 5.0.3 on 2024-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otprecord_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq_title', models.CharField(max_length=255)),
                ('faq_description', models.TextField()),
                ('faq', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
