# Generated by Django 5.0.3 on 2024-04-02 17:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servicepages'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepages',
            name='certificate_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='registration_title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='service_description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='service_title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='step_by_step_description',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='step_by_step_title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='what_is',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='servicepages',
            name='faq',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='servicepages',
            name='faq_description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='servicepages',
            name='faq_title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
