# Generated by Django 5.0.3 on 2024-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_servicepages_certificate_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepages',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
