# Generated by Django 5.0.3 on 2024-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_servicepages_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepages',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
