# Generated by Django 5.0.3 on 2024-04-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_state_alter_user_email'),
        ('accounts', '0006_servicepages_slug'),
    ]

    operations = [
    ]
