# Generated by Django 5.0.3 on 2024-04-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
        ('accounts', '0007_merge_20240407_1928'),
    ]

    operations = [
    ]
