# Generated by Django 5.0.3 on 2024-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_workorder_servicepages_required_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
