# Generated by Django 5.0.3 on 2024-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_workorder_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
