# Generated by Django 5.0.3 on 2024-04-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_workorder_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderFiles',
        ),
    ]
