# Generated by Django 5.0.3 on 2024-04-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_workorderfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='files',
            field=models.FileField(default='', upload_to='work_order_files/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_files', to='accounts.servicepages'),
        ),
    ]
