# Generated by Django 5.0.3 on 2024-04-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_workorder_files_workorder_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='files',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='service',
        ),
        migrations.CreateModel(
            name='WorkOrderFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(default='', upload_to='work_order_files/')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_files', to='accounts.servicepages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
