# Generated by Django 5.0.3 on 2024-04-11 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_workorder_files_remove_workorder_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorderfiles',
            name='files',
            field=models.FileField(upload_to='work_order_files/'),
        ),
        migrations.AlterField(
            model_name='workorderfiles',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_files', to='accounts.servicepages'),
        ),
    ]
