# Generated by Django 5.0.3 on 2024-04-11 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_workorder_user_alter_workorderfiles_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
