# Generated by Django 5.0.3 on 2024-04-11 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_workorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
