# Generated by Django 5.0.3 on 2024-04-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_workorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[(1, 'Available'), (2, 'Inprocess'), (3, 'Canceled')]),
        ),
    ]
