# Generated by Django 5.0.3 on 2024-04-11 16:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_workorder_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderfiles',
            name='file_name',
            field=models.CharField(default='file name', max_length=255),
        ),
        migrations.AddField(
            model_name='workorderfiles',
            name='work_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='accounts.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[(1, 'Available'), (2, 'Inprocess'), (3, 'Canceled')], null=True),
        ),
    ]
