# Generated by Django 5.0.3 on 2024-04-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_work_order_id_workorderfiles_work_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderfiles',
            old_name='service',
            new_name='service_id',
        ),
        migrations.RenameField(
            model_name='workorderfiles',
            old_name='work_order',
            new_name='work_order_id',
        ),
    ]
