# Generated by Django 5.0.3 on 2024-04-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_service_workorderfiles_service_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderfiles',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='workorderfiles',
            old_name='work_order_id',
            new_name='work_order',
        ),
    ]
