# Generated by Django 5.0.3 on 2024-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepages',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Business Essentials'), (2, 'Tax Related'), (3, 'Entity Formation'), (4, 'Income Tax'), (5, 'GST'), (6, 'Accounting'), (7, 'Company Compliance'), (8, 'TDS')], default=None, null=True),
        ),
    ]
