# Generated by Django 5.0.3 on 2024-04-22 09:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_servicepages_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.servicepages',),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='listing_price'),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='client_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Proprietorship'), (3, 'Firm'), (4, 'LLP'), (5, 'Company'), (6, 'Trust')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='effective_price'),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='due_duration',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Half-Yearly'), (6, 'Yearly')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='servicepages',
            name='government_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
