# Generated by Django 5.0.3 on 2024-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_workorderdocument_delete_workorderfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Proprietorship'), (3, 'Firm'), (4, 'LLP'), (5, 'Company'), (6, 'Trust')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('Technology and IT', 'Technology and IT'), ('Healthcare and pharmaceuticals', 'Healthcare and pharmaceuticals'), ('Finance and banking', 'Finance and banking'), ('Manufacturing and production', 'Manufacturing and production'), ('Retail and e-commerce', 'Retail and e-commerce'), ('Energy and utilities', 'Energy and utilities'), ('Transportation and logistics', 'Transportation and logistics'), ('Media and entertainment', 'Media and entertainment'), ('Food and beverage', 'Food and beverage'), ('Hospitality and tourism', 'Hospitality and tourism')], default='PLEASE SELECT INDUSTRY TYPE', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('Trading', 'Trading')], default='PLEASE SELECT Nature of business', null=True),
        ),
    ]
