# Generated by Django 5.0.3 on 2024-04-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_user_client_type_user_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='ended_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='frequency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requested_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_dept',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='WorkOrderDownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_document', models.FileField(upload_to='work_order_download_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
