# Generated by Django 5.0.3 on 2024-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_workorder_client_id_workorder_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Upload'), (3, 'Inprocess'), (4, 'Pay'), (5, 'Download')], default=1, null=True),
        ),
    ]
