# Generated by Django 5.0.3 on 2024-04-30 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='client_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='frequency',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='WorkorderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('recipient_name', models.CharField(max_length=255)),
                ('qr_code_url', models.URLField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
