# Generated by Django 5.0.3 on 2024-04-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_upcomingduedates'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderdocument',
            name='uploaded_by_beyondtax',
            field=models.BooleanField(default=False),
        ),
    ]
