# Generated by Django 5.0.3 on 2024-05-25 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_upcomingduedates_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number can be only 10 digits.', regex='^([1-9][0-9]{9})$')]),
        ),
    ]
