# Generated by Django 5.0.3 on 2024-05-22 23:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_user_email_alter_workorder_client_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingduedates',
            name='data',
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='compliance_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='department',
            field=models.IntegerField(blank=True, choices=[(1, 'Business Essentials'), (2, 'Tax Related'), (3, 'Entity Formation'), (4, 'Income Tax'), (5, 'GST'), (6, 'Accounting'), (7, 'Company Compliance'), (8, 'TDS')], null=True),
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='penalty_fine_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30),
        ),
        migrations.AddField(
            model_name='user',
            name='business_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='business_mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_formation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_employees',
            field=models.CharField(blank=True, choices=[('Upto 5 Employees', 'Upto 5 Employees'), ('Upto 25 Employees', 'Upto 25 Employees'), ('Above 25 Employees', 'Above 25 Employees')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepages',
            name='certificate_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Proprietorship'), (3, 'HUF'), (4, 'Firm'), (5, 'LLP'), (6, 'Private Limited Company'), (7, 'Public Limited Company'), (8, 'Trust')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('Consultancy', 'Consultancy'), ('Technology', 'Technology'), ('Construction', 'Construction'), ('Clothing', 'Clothing'), ('Agriculture', 'Agriculture'), ('Salaried', 'Salaried'), ('Real Estate', 'Real Estate'), ('Food & beverage', 'Food & beverage'), ('Consulting', 'Consulting'), ('Rental', 'Rental'), ('Sports', 'Sports'), ('Decors', 'Decors'), ('Retail', 'Retail'), ('Healthcare', 'Healthcare')], default='PLEASE SELECT INDUSTRY TYPE', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number can be only 10 digits.', regex='^([1-9][0-9]{9})$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], default='PLEASE SELECT Nature of business', null=True),
        ),
    ]
