# Generated by Django 5.0.3 on 2024-05-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='service',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workorderdocument',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='workorderdownloaddocument',
            name='work_order',
        ),
        migrations.DeleteModel(
            name='WorkorderPayment',
        ),
        migrations.DeleteModel(
            name='WorkOrderDocument',
        ),
    ]
