# Generated by Django 5.0.3 on 2024-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_email',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact_person_phone_number',
            new_name='business_mobile_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact_person',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128),
        ),
    ]
