# Generated by Django 5.0.3 on 2024-05-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_workorder_service_remove_workorder_user_and_more'),
        ('payments', '0004_alter_payment_work_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='WorkOrderDownloadDocument',
        ),
    ]
