# Generated by Django 5.0.3 on 2024-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Proprietorship'), (3, 'HUF'), (4, 'Firm'), (5, 'LLP'), (6, 'Private Limited Company'), (7, 'Public Limited Company'), (8, 'Trust')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('Consultancy', 'Consultancy'), ('Technology', 'Technology'), ('Construction', 'Construction'), ('Clothing', 'Clothing'), ('Agriculture', 'Agriculture'), ('Salaried', 'Salaried'), ('Real Estate', 'Real Estate'), ('Food & beverage', 'Food & beverage'), ('Consulting', 'Consulting'), ('Rental', 'Rental'), ('Sports', 'Sports'), ('Decors', 'Decors'), ('Retail', 'Retail'), ('Healthcare', 'Healthcare')], default='PLEASE SELECT INDUSTRY TYPE', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler')], default='PLEASE SELECT Nature of business', null=True),
        ),
    ]
