# Generated by Django 5.0.3 on 2024-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_user_client_type_alter_user_industry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_revenue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_formation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_employees',
            field=models.CharField(blank=True, choices=[('Upto 5 Employees', 'Upto 5 Employees'), ('Upto 25 Employees', 'Upto 25 Employees'), ('Above 25 Employees', 'Above 25 Employees')], max_length=50, null=True),
        ),
    ]
