# Generated by Django 5.0.3 on 2024-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='source',
            field=models.IntegerField(blank=True, choices=[(1, 'Email'), (2, 'Mobile')], default=None, null=True),
        ),
    ]
