# Generated by Django 5.0.3 on 2024-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_otprecord_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
