# Generated by Django 5.0.3 on 2024-05-21 18:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_user_annual_revenue_user_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepages',
            name='certificate_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30),
        ),
    ]
