# Generated by Django 5.0.3 on 2024-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_otprecord_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
