# Generated by Django 5.0.3 on 2024-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_servicepages_certificate_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingduedates',
            name='data',
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='compliance_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='department',
            field=models.CharField(blank=True, choices=[(1, 'Business Essentials'), (2, 'Tax Related'), (3, 'Entity Formation'), (4, 'Income Tax'), (5, 'GST'), (6, 'Accounting'), (7, 'Company Compliance'), (8, 'TDS')], default='Please Select Department', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upcomingduedates',
            name='penalty_fine_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
