# Generated by Django 5.0.3 on 2024-06-04 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_otprecord_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContactPersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('preferred_timing', models.CharField(blank=True, choices=[('9AM - 12PM', '9AM - 12PM'), ('12PM - 5PM', '12PM - 5PM')], null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number can be only 10 digits.', regex='^([1-9][0-9]{9})$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
