# Generated by Django 5.0.3 on 2024-06-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_otprecord_otp_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otprecord',
            name='otp_session_id',
        ),
    ]
