# Generated by Django 5.0.3 on 2024-09-13 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_remove_otprecord_otp_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="PAN number must be in format 'ABCDE1234F'", regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='government_id_proofs/pan/')),
                ('is_pan_verified', models.BooleanField(default=False)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be 12 digits', regex='^[0-9]{12}$')])),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='government_id_proofs/aadhar/')),
                ('is_aadhaar_verified', models.BooleanField(default=False)),
                ('driving_license_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Driving License number must be in format 'AB1234567890123'", regex='^[A-Z]{2}[0-9]{13}$')])),
                ('driving_license_card', models.FileField(blank=True, null=True, upload_to='government_id_proofs/driving_license/')),
                ('driving_license_validity', models.DateField(blank=True, null=True)),
                ('is_driving_license_verified', models.BooleanField(default=False)),
                ('voter_id_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Voter ID number must be in format 'ABC1234567'", regex='^[A-Z]{3}[0-9]{7}$')])),
                ('voter_id_card', models.FileField(blank=True, null=True, upload_to='government_id_proofs/voter_id/')),
                ('is_voter_id_verified', models.BooleanField(default=False)),
                ('ration_card_no', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Ration Card number must be between 10 and 12 characters', regex='^[A-Z0-9]{10,12}$')])),
                ('ration_card_file', models.FileField(blank=True, null=True, upload_to='government_id_proofs/ration_card/')),
                ('is_ration_card_verified', models.BooleanField(default=False)),
                ('passport_no', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message="Passport number must be in format 'A1234567'", regex='^[A-Z][0-9]{7}$')])),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='government_id_proofs/passport/')),
                ('passport_validity', models.DateField(blank=True, null=True)),
                ('is_passport_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.IntegerField(choices=[(1, 'Communication Address'), (2, 'Permanent Address')], default=1)),
                ('rent_status', models.IntegerField(choices=[(1, 'Owned'), (2, 'Rented')])),
                ('rental_agreement', models.FileField(upload_to='rental_agreements/')),
                ('door_no', models.CharField(blank=True, max_length=255)),
                ('permise_name', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileBankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.CharField(blank=True, max_length=255)),
                ('ifsc_code', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Savings Account'), (2, 'Current Account')])),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('maritual_status', models.IntegerField(choices=[(1, 'married'), (2, 'unmarried'), (3, 'prefer not to disclose')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
