# Generated by Django 5.0.3 on 2024-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_profileaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformation',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
