# Generated by Django 5.0.3 on 2024-09-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_profileinformation_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinformation',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='profileinformation',
            name='maritual_status',
            field=models.IntegerField(blank=True, choices=[(1, 'married'), (2, 'unmarried'), (3, 'prefer not to disclose')], null=True),
        ),
    ]
