# Generated by Django 5.0.3 on 2024-09-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_profileinformation_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileaddress',
            name='rent_status',
            field=models.IntegerField(choices=[(1, 'Owned'), (2, 'Rented')], default=1),
        ),
        migrations.AlterField(
            model_name='profileaddress',
            name='rental_agreement',
            field=models.FileField(blank=True, upload_to='rental_agreements/'),
        ),
    ]
