# Generated by Django 5.0.3 on 2024-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_alter_profileaddress_rent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
