# Generated by Django 5.0.3 on 2024-09-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_user_temp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temp_email',
        ),
    ]
