# Generated by Django 5.1.1 on 2024-09-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_remove_user_temp_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentid',
            old_name='passport_file',
            new_name='passport',
        ),
        migrations.RenameField(
            model_name='governmentid',
            old_name='ration_card_file',
            new_name='ration_card',
        ),
    ]
