# Generated by Django 5.0.3 on 2024-09-19 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_rename_passport_file_governmentid_passport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorshipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('pan_of_company', models.CharField(max_length=10)),
                ('company_type', models.CharField(blank=True, choices=[('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited')], null=True)),
                ('isin_code', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EsopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_name', models.CharField(max_length=255)),
                ('pan_of_company', models.CharField(max_length=10)),
                ('company_type', models.CharField(blank=True, choices=[('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited')], null=True)),
                ('dpit_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_deferred', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_tax_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialOwnershipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_partner_in_firm', models.BooleanField(default=False)),
                ('has_unlisted_shares', models.BooleanField(default=False)),
                ('is_director_in_company', models.BooleanField(default=False)),
                ('has_esops', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_ownership_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnFilingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_filed_under', models.CharField(blank=True, choices=[('Section 139(1)', 'Section 139(1) - On or before the due date'), ('Section 139(4)', 'Section 139(4) - Belated return'), ('Section 139(5)', 'Section 139(5) - Revised return'), ('Section 139(3)', 'Section 139(3) - Loss return'), ('Section 92CD', 'Section 92CD - Modified return under APA'), ('Section 119(2)(b)', 'Section 119(2)(b) - Return after condonation of delay')], null=True)),
                ('return_type', models.CharField(blank=True, choices=[('Original', 'Original'), ('Revised', 'Revised'), ('Modified', 'Modified'), ('Belated', 'Belated')], null=True)),
                ('has_representative_access', models.CharField(blank=True, choices=[('Legal Representative', 'Legal Representative'), ('Agent', 'Agent'), ('Guardian', 'Guardian'), ('Trustee', 'Trustee'), ('Any other person representing the assessee', 'Any other person representing the assessee')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_filing_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnlistedShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('pan_of_company', models.CharField(max_length=10)),
                ('company_type', models.CharField(blank=True, choices=[('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited')], null=True)),
                ('isin_code', models.CharField(blank=True, max_length=12, null=True)),
                ('face_price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price_per_share', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlisted_share_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
